#ifndef _REQUESTS_HANDLERS_H
# define _REQUESTS_HANDLERS_H

# define TYPE_T_REQUEST_INIT 0
# define TYPE_T_REQUEST_COMPUTATION 1
# define TYPE_T_REQUEST_FINISH 2
# define TYPE_T_REQUEST_DROP 3

# define TYPE_T_RESPONSE_SUCCESS 0
# define TYPE_T_RESPONSE_UNRECOGNIZED 1
# define TYPE_T_RESPONSE_SYSTEM 2

#endif